### ISSUE TITLE
Example code does not work for me, responds with nil

### ISSUE THREAD

**Issue by jsaak** [socketry/db-mariadb#1]
I tried to query a mariadb server using this example code:
https://socketry.github.io/db/guides/getting-started/index.html

And i do not get any results.

According to strace mariadb answers, but i can not see it in ruby.

```
$ ruby --version        
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
```

prettyprinting objects:
```
pp session
#<DB::Context::Session:0x000056262e4cad38
 @connection=nil,
 @pool=
  #<Async::Pool::Controller:0x000056262e795248
   @available=[],
   @constructor=
    #<DB::MariaDB::Adapter:0x000056262e7954a0
     @options=
      {:database=>"autotest_jsaak",
       :username=>"autotest_jsaak_user",
       :password=>"autotest_jsaak_pw",
       :port=>3306}>,
   @gardener=nil,
   @guard=
    #<Async::Semaphore:0x000056262e794ff0
     @count=0,
     @limit=1,
     @parent=nil,
     @waiting=[]>,
   @limit=nil,
   @notification=#<Async::Notification:0x000056262e795108 @waiting=[]>,
   @resources={}>>

pp client
#<DB::Client:0x000056262e7953b0
 @adapter=
  #<DB::MariaDB::Adapter:0x000056262e7954a0
   @options=
    {:database=>"autotest_jsaak",
     :username=>"autotest_jsaak_user",
     :password=>"autotest_jsaak_pw",
     :port=>3306}>,
 @pool=
  #<Async::Pool::Controller:0x000056262e795248
   @available=[],
   @constructor=
    #<DB::MariaDB::Adapter:0x000056262e7954a0
     @options=
      {:database=>"autotest_jsaak",
       :username=>"autotest_jsaak_user",
       :password=>"autotest_jsaak_pw",
       :port=>3306}>,
   @gardener=nil,
   @guard=
    #<Async::Semaphore:0x000056262e794ff0
     @count=0,
     @limit=1,
     @parent=nil,
     @waiting=[]>,
   @limit=nil,
   @notification=#<Async::Notification:0x000056262e795108 @waiting=[]>,
   @resources={}>>

pp result
nil
```

strace log
```
sendto(5, "\21\0\0\0\3SELECT VERSION()", 21, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 21
recvfrom(5, 0x5652f201d350, 16384, MSG_DONTWAIT, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
epoll_ctl(8, EPOLL_CTL_ADD, 5, {EPOLLIN, {u32=5, u64=8589934597}}) = -1 EEXIST (File exists)
epoll_wait(8, [{EPOLLIN, {u32=5, u64=4294967301}}], 64, 59743) = 1
recvfrom(5, "\1\0\0\1\1\37\0\0\2\3def\0\0\0\tVERSION()\0\f\10\0\31\0"..., 16384, MSG_DONTWAIT, NULL, NULL) = 88
epoll_wait(8, [{EPOLLIN|EPOLLHUP, {u32=5, u64=4294967301}}], 64, 1000) = 1
epoll_ctl(8, EPOLL_CTL_DEL, 5, 0x5652f1b07d80) = 0
```

**Comment by ioquatix** [comment]
Okay, I'll check it.

**Comment by ioquatix** [comment]
Okay, so initially I went into this wondering why I made this change. Before this used to work and now it doesn't. But for the low level database driver, it's a little bit more complex.

Surprisingly, the general idea that databases are `request` -> `response` is incorrect. It's possible to buffer/stream multiple queries and read multiple results/recordsets.

A big part of this is, it's impossible to generally know how many results would be returned from a given query.

While there are some general high level expectations, this isn't a given at the database driver level.

We could rewrite `call` as this:

```
			# Send a query to the server.
			# @parameter statement [String] The SQL query to send.
			def call(statement, **options)
				connection = self.connection
				
				connection.send_query(statement, **options)
				
				if block_given?
					yield connection
				else
					return connection.next_result
				end
			ensure
				self.close
			end
```

This is a little bit more forgiving if no block is given. But as soon as someone writes:

```
session.call("SELECT 1; SELECT 2")
```

it breaks.

Also, the life cycle guarantee of the connection is more tricky to manage. The above code actually won't work because the resulting recordset might stilll use the underlying connection but when we leave the function we call `self.close` to release the connection back to the pool.

Therefore, I think this is a documentation problem rather than a code problem, so I'll fix the examples and also add documentation to clearly outline the intended usage.

**Comment by jsaak** [comment]
I do not really understand the problem.
I think a db connection is just like a http connection. One request - one response. The response could be streaming.

Also ``` session.call("SELECT 1; SELECT 2") ``` is a bad idea, most database drivers forbid this because of possible SQL injection reasons.. And I do not see any real life benefit to allow more than one statement.

I need a robust mariadb dirver: Do not you think i could integrate https://github.com/brianmario/mysql2  with async?
Mysql C API can set non-blocking mode and exposes the file descriptor. I think I could register that file descriptor somehow to the reactor. Can you please help me how to do that?

**Comment by ioquatix** [comment]
The example code should work correctly now.
